default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hummingbird_development

test:
  <<: *default
  database: hummingbird_test

production:
  <<: *default
  database: hummingbird_production
  username: hummingbird
  password: <%= ENV['hummingbird_DATABASE_PASSWORD'] %>